### ISSUE TITLE
Non prise en compte des captures de raids non éclos

### ISSUE THREAD

**Issue by JeBaWiart** [Ninadjeret/profchen-map#28]
Certaines images sont prises en compte par le bot, d'autres non. 
Cela ne se produit que lorsque ce sont des raids non éclos.

En fichier joint un raid OK et un raid KO.
![raid2_bot_ok](https://user-images.githubusercontent.com/25139958/49177179-d74cd180-f34c-11e8-8dbf-f327f152628b.png)

![raid2_bot_ko](https://user-images.githubusercontent.com/25139958/49177232-f64b6380-f34c-11e8-8151-30aa09c598e5.png)

**Comment by Ninadjeret** [comment]
Hello 👋 Le problème vient d'un ratio d'écran jusqu'alors mal supporté. Certains téléphones avec des résolution 18/9 pouvaient, en fonction de l'épaisseur, de la barre de navigation

**Comment by Ninadjeret** [comment]
C'est maintenant correctement supporté :)

**Comment by JeBaWiart** [comment]
Nice, rapide pour la correction!

Super boulot en tout cas :)


Le mer. 28 nov. 2018 à 21:31, Florian Chaillou <notifications@github.com> a
écrit :
